// Calls native script functions through the engine's dispatch table.
//
// This uses CFunction::call_native rather than CFunction::execute. execute()
// goes through CFunction::execute_native, whose address is not reachable from a
// name anchor and therefore goes stale on every game patch. call_native indexes
// the global native table with the CFunction's own registration_offset instead,
// and every address it needs can be regenerated by tools/w3offsets.
//
// Neither engine global this needs is hardcoded by hand:
//
//   * the CR4Game CClass comes from CR4GameClassBuilder's `cls` field, which
//     w3offsets locates through MSVC RTTI;
//   * the live CR4Game instance is found at runtime by scanning the image's
//     writable data for a pointer to an object whose vtable is CR4Game's
//     primary vtable - also RTTI-derived. See find_instance_slots().
//
// The probes are ordered to isolate failures: a primitive round trip first,
// then a String out, then a String in, then a multi-argument call, then the
// primitive again to confirm the stack survived.

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#include <Windows.h>

#include <red3lib/RED3lib.hpp>
#include <red3lib/detail/Addresses.hpp>
#include <red3lib/detail/Relocation.hpp>

#define RED3LIB_C_EXPORT extern "C" __declspec(dllexport)
#define RED3LIB_CALL __fastcall

enum class EMainReason : std::uint8_t
{
    Load = 0,
    Unload
};

namespace
{
// ---------------------------------------------------------------------------
// Regenerate with:  python tools/w3offsets/w3offsets.py --classes CR4Game
//
// Both values are name-anchored, so a game patch only means re-running the
// extractor. Neither was found by hand.
// ---------------------------------------------------------------------------
// RED3ext compares this against the numeric VS_FIXEDFILEINFO fields, which
// encode this build as 4.0.1.37654 even though its FileVersion string reads
// "4.0.0.103190" (103190 = 0x19316 overflows the 16-bit revision field).
constexpr const char* supported_version = "4.0.1.37654";

// CR4GameClassBuilder's instance + 0x8, i.e. IClassBuilder::cls. The builder's
// constructor zeroes exactly this address, which is what confirms the offset.
constexpr std::uintptr_t cr4game_class_offset = 0x145a82c70 - 0x140000000;

// CR4Game's primary vtable: the complete-object locator whose subobject offset
// is 0. CR4Game uses multiple inheritance, so its other three vtables are the
// wrong fingerprint for identifying an instance.
constexpr std::uintptr_t cr4game_vtable_offset = 0x142d0ee38 - 0x140000000;

std::string narrow(const wchar_t* text, std::uint32_t length)
{
    if (!text || length == 0)
    {
        return {};
    }

    auto needed = WideCharToMultiByte(CP_UTF8, 0, text, static_cast<int>(length), nullptr, 0, nullptr, nullptr);
    if (needed <= 0)
    {
        return {};
    }

    std::string out(static_cast<std::size_t>(needed), '\0');
    WideCharToMultiByte(CP_UTF8, 0, text, static_cast<int>(length), out.data(), needed, nullptr, nullptr);
    return out;
}

// Probe output goes to a file next to the plugin as well as to stdout: a game
// process has no console unless RED3ext's dev console is enabled, and even then
// the window cannot be read back afterwards. Every line is flushed so a crash
// mid-probe still leaves the results on disk.
std::ofstream g_log;

struct Tee
{
    template<typename T>
    Tee& operator<<(const T& value)
    {
        std::cout << value;
        if (g_log)
            g_log << value;
        return *this;
    }

    Tee& operator<<(std::ostream& (*manip)(std::ostream&))
    {
        std::cout << manip;
        if (g_log)
            g_log << manip;
        return *this;
    }

    Tee& operator<<(std::ios_base& (*manip)(std::ios_base&))
    {
        std::cout << manip;
        if (g_log)
            g_log << manip;
        return *this;
    }
};

Tee out;

void open_log(HMODULE self)
{
    wchar_t path[MAX_PATH]{};
    if (GetModuleFileNameW(self, path, MAX_PATH) == 0)
    {
        return;
    }

    std::filesystem::path file = path;
    file.replace_filename(L"probes.log");
    g_log.open(file, std::ios::out | std::ios::trunc);
}

// A committed, readable span of the address space.
struct Region
{
    const std::uint8_t* begin;
    const std::uint8_t* end;
};

// Snapshot every readable region once, then answer readability by binary search.
// The previous version called VirtualQuery per candidate pointer with a
// one-entry cache; candidates alternate between regions often enough that the
// cache thrashed, and the whole scan then ran again on the next frame. That is
// tens of thousands of syscalls per frame on the game's main thread, which
// presents as a hang rather than a stutter.
std::vector<Region> snapshot_readable_regions()
{
    constexpr DWORD readable = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READ |
                               PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;

    SYSTEM_INFO si{};
    GetSystemInfo(&si);

    std::vector<Region> regions;
    auto* cursor = static_cast<const std::uint8_t*>(si.lpMinimumApplicationAddress);
    const auto* limit = static_cast<const std::uint8_t*>(si.lpMaximumApplicationAddress);

    MEMORY_BASIC_INFORMATION info{};
    while (cursor < limit && VirtualQuery(cursor, &info, sizeof(info)) == sizeof(info))
    {
        const auto* base = static_cast<const std::uint8_t*>(info.BaseAddress);
        if (info.State == MEM_COMMIT && (info.Protect & readable) != 0 && (info.Protect & PAGE_GUARD) == 0)
        {
            regions.push_back({base, base + info.RegionSize});
        }

        auto* next = base + info.RegionSize;
        if (next <= cursor)
        {
            break;
        }
        cursor = next;
    }

    return regions;
}

bool is_readable(const std::vector<Region>& regions, const void* address, std::size_t size)
{
    const auto* p = static_cast<const std::uint8_t*>(address);
    auto it = std::upper_bound(regions.begin(), regions.end(), p,
                               [](const std::uint8_t* v, const Region& r) { return v < r.begin; });
    if (it == regions.begin())
    {
        return false;
    }

    --it;
    return p >= it->begin && p + size <= it->end;
}

// Find globals holding a pointer to an instance of the class owning `vtable`.
//
// A singleton like GGame is a plain data global, written once through the
// engine's generic RTTI create-object path, so nothing about its call site
// identifies it statically. Its contents are identifiable though: the object it
// points at begins with a vtable pointer, and that vtable is reachable by name
// through RTTI. Scanning for the relationship finds the global on any build.
std::vector<void**> find_instance_slots(const void* vtable, std::size_t limit)
{
    std::vector<void**> found;

    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandle(nullptr));
    if (!base)
    {
        return found;
    }

    auto* dos = reinterpret_cast<IMAGE_DOS_HEADER*>(base);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE)
    {
        return found;
    }

    auto* nt = reinterpret_cast<IMAGE_NT_HEADERS*>(base + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE)
    {
        return found;
    }

    const auto regions = snapshot_readable_regions();

    auto* section = IMAGE_FIRST_SECTION(nt);
    auto section_count = static_cast<std::size_t>(nt->FileHeader.NumberOfSections);

    for (std::size_t i = 0; i < section_count; i++, section++)
    {
        // Writable and not executable: where a singleton pointer would live.
        if ((section->Characteristics & IMAGE_SCN_MEM_WRITE) == 0)
        {
            continue;
        }

        if ((section->Characteristics & IMAGE_SCN_MEM_EXECUTE) != 0)
        {
            continue;
        }

        auto* slots = reinterpret_cast<void**>(base + section->VirtualAddress);
        auto count = static_cast<std::size_t>(section->Misc.VirtualSize) / sizeof(void*);
        if (count == 0 || !is_readable(regions, slots, sizeof(void*)))
        {
            continue;
        }

        for (std::size_t k = 0; k < count; k++)
        {
            auto* candidate = slots[k];
            if (!candidate || (reinterpret_cast<std::uintptr_t>(candidate) & 7u) != 0)
            {
                continue;
            }

            if (!is_readable(regions, candidate, sizeof(void*)))
            {
                continue;
            }

            if (*reinterpret_cast<void* const*>(candidate) != vtable)
            {
                continue;
            }

            found.push_back(&slots[k]);
            if (found.size() >= limit)
            {
                return found;
            }
        }
    }

    return found;
}

// Primary vtables, RTTI-derived (python w3offsets.py --classes CR4Player ...).
// An object's vptr names its most-derived NATIVE class - a script class such as
// W3PlayerWitcher is instantiated on its nearest native base and carries that
// base's vptr, so CR4Player is what a player object reports.
struct known_class
{
    const char* name;
    std::uintptr_t vtable_offset;
};

constexpr known_class known_classes[] = {
    {"CR4Player", 0x2d71520}, {"CPlayer", 0x2b3fea8}, {"CNewNPC", 0x2b4bd68},
    {"CActor", 0x2b3ce38},    {"CEntity", 0x2a211a8}, {"CR4Game", 0x2d0ee38},
};

// A returned pointer is engine-controlled and might be a handle, a null, or
// something unmapped - check before dereferencing it.
bool readable(const void* address, std::size_t size)
{
    MEMORY_BASIC_INFORMATION info{};
    if (VirtualQuery(address, &info, sizeof(info)) == 0)
    {
        return false;
    }

    constexpr DWORD ok = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE |
                         PAGE_EXECUTE_WRITECOPY;
    if (info.State != MEM_COMMIT || (info.Protect & ok) == 0 || (info.Protect & PAGE_GUARD) != 0)
    {
        return false;
    }

    const auto* begin = static_cast<const std::uint8_t*>(info.BaseAddress);
    return static_cast<const std::uint8_t*>(address) + size <= begin + info.RegionSize;
}

// Report what an engine-returned object actually is, using the CEntity field
// offsets the RTTI dump gives us.
void describe_object(const char* indent, void* object)
{
    if (!object || !readable(object, 512))
    {
        out << indent << "not a readable object" << std::endl;
        return;
    }

    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandle(nullptr));
    auto* vptr = *reinterpret_cast<std::uint8_t**>(object);

    const char* name = "<not a known class>";
    for (const auto& kc : known_classes)
    {
        if (vptr == base + kc.vtable_offset)
        {
            name = kc.name;
            break;
        }
    }

    out << indent << "vptr = " << static_cast<void*>(vptr) << "  (image+0x" << std::hex
        << static_cast<std::size_t>(vptr - base) << std::dec << ")  class = " << name << std::endl;

    auto* bytes = reinterpret_cast<std::uint8_t*>(object);
    bool guid_set = false;
    for (int i = 0; i < 16; i++)
    {
        if (bytes[204 + i])
        {
            guid_set = true;
        }
    }

    const auto& tags = *reinterpret_cast<red3lib::TDynArray<void*>*>(bytes + 192);
    out << indent << "guid set = " << std::boolalpha << guid_set << ", tags = { entries "
        << static_cast<const void*>(tags.entries) << ", count " << tags.size << " }" << std::endl;
}

// Dump the raw 12 bytes as well as the decoded text. The byte view is the point
// of the exercise: it shows the field order directly, and whether "size"
// includes the terminating null.
void dump_string(const char* label, const red3lib::String& value)
{
    out << "  " << label << " raw =";

    const auto* raw = reinterpret_cast<const std::uint8_t*>(&value);
    for (std::size_t i = 0; i < sizeof(red3lib::String); i++)
    {
        out << ' ' << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(raw[i]);
    }

    out << std::dec << "\n    data = " << static_cast<const void*>(value.data) << ", size = " << value.size
        << ", text = \"" << narrow(value.data, value.size) << "\"" << std::endl;
}

red3lib::CFunction* resolve(red3lib::CClass* cls, const wchar_t* name)
{
    auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));

    auto function = cls->find_function(name);
    if (!function)
    {
        out << "  [skip] " << narrowed << " not found on the class chain" << std::endl;
        return nullptr;
    }

    if (!function->is_native())
    {
        out << "  [skip] " << narrowed << " is scripted, not native" << std::endl;
        return nullptr;
    }

    return function;
}

// Returns false while the game object does not exist yet, so Update() retries.
// Per-function metadata. If registration_offset is nonsense, or impl does not
// land in the game's .text, then call_native is dispatching to the wrong entry
// and no amount of stack-frame fiddling will help.
void dump_meta(const char* label, red3lib::CFunction* fn)
{
    const void* impl = nullptr;
    if (fn->registration_offset >= 0)
    {
        const auto index = static_cast<std::size_t>(fn->registration_offset);
        if (fn->is_global())
        {
            red3lib::detail::RelocArray<red3lib::CFunction::native_fn_t> table(
                red3lib::detail::addresses::CFunction::native_table);
            impl = reinterpret_cast<const void*>(table[index]);
        }
        else
        {
            red3lib::detail::RelocArray<red3lib::CFunction::native_method_entry> table(
                red3lib::detail::addresses::CFunction::class_method_table);
            impl = reinterpret_cast<const void*>(table[index].code);
        }
    }

    out << "    [" << label << "] flags=0x" << std::hex << fn->flags << std::dec << " params=" << fn->params.size
        << " locals=" << fn->locals.size << " stackSize=" << fn->stack_size << " regOffset=" << fn->registration_offset
        << " impl=" << impl << std::endl;
}

red3lib::CClass* g_class = nullptr;
red3lib::IScriptable* g_context = nullptr;

// Locate the class and the live instance. Cached: the address-space scan is
// expensive and must not be repeated once it has succeeded.
bool locate()
{
    if (g_class && g_context)
    {
        return true;
    }

    red3lib::detail::RelocPtr<red3lib::CClass> game_class(cr4game_class_offset);
    if (game_class == nullptr)
    {
        return false;
    }

    red3lib::detail::RelocArray<std::uint8_t> vtable(cr4game_vtable_offset);
    auto slots = find_instance_slots(vtable.data(), 8);
    if (slots.empty())
    {
        return false;
    }

    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandle(nullptr));
    g_class = game_class.get();
    g_context = static_cast<red3lib::IScriptable*>(*slots.front());

    out << "located CR4Game\n"
        << "  CClass   = " << static_cast<const void*>(g_class) << "\n"
        << "  vtable   = " << static_cast<const void*>(vtable.data()) << "\n"
        << "  instance = " << static_cast<const void*>(g_context) << " via " << slots.size() << " global(s)"
        << std::endl;
    for (auto* slot : slots)
    {
        out << "    +0x" << std::hex << static_cast<std::size_t>(reinterpret_cast<std::uint8_t*>(slot) - base)
            << std::dec << std::endl;
    }
    return true;
}

// One round of probes. Repeated as the game progresses: values that are zero at
// the menu but populated in-world tell us the earlier run was simply too early,
// rather than the marshalling being wrong.
void run_round(int round)
{
    out << "\n--- round " << round << " ---" << std::endl;

    if (auto* fn = resolve(g_class, L"GetEngineTimeAsSeconds"))
    {
        dump_meta("GetEngineTimeAsSeconds", fn);
        out << "  GetEngineTimeAsSeconds() = " << fn->call_native<float>(g_context) << std::endl;
    }

    if (auto* fn = resolve(g_class, L"GetApplicationVersion"))
    {
        dump_meta("GetApplicationVersion", fn);
        auto version = fn->call_native<red3lib::String>(g_context);
        dump_string("GetApplicationVersion() ->", version);
    }

    // A one-argument call. String arguments are deliberately not probed: they
    // are 12 bytes and the VM has no immediate opcode for that width, so
    // CStackFrameCodeWriter rejects them at compile time rather than letting the
    // call corrupt the code stream. GetTimeScale takes a bool, which encodes as
    // a 1-byte immediate.
    if (auto* fn = resolve(g_class, L"GetTimeScale"))
    {
        dump_meta("GetTimeScale", fn);
        out << "  GetTimeScale(true) = " << fn->call_native<float>(g_context, true) << std::endl;
    }

    // A String argument, tested so the result actually discriminates.
    //
    // IsPausedForReason returning false proves nothing: it is false whether or
    // not the argument arrived, which is exactly what the broken encoding also
    // produced. Pause keys on the string, so setting the state and reading it
    // back can only agree if the content survived both calls. Unpause restores
    // it either way.
    if (auto* is_paused = resolve(g_class, L"IsPausedForReason"))
    {
        dump_meta("IsPausedForReason", is_paused);

        static wchar_t reason[] = L"RED3lib";
        auto arg = red3lib::borrow_string(reason); // sized the way the engine sizes its own

        out << std::boolalpha << "  IsPausedForReason before = " << is_paused->call_native<bool>(g_context, arg)
            << std::endl;

        if (auto* pause = resolve(g_class, L"Pause"))
        {
            pause->call_native<void>(g_context, arg);
            out << "  IsPausedForReason after Pause = " << is_paused->call_native<bool>(g_context, arg)
                << "   <-- true proves the string content was delivered" << std::endl;
        }

        if (auto* unpause = resolve(g_class, L"Unpause"))
        {
            unpause->call_native<void>(g_context, arg);
            out << "  IsPausedForReason after Unpause = " << is_paused->call_native<bool>(g_context, arg) << std::endl;
        }
    }

    if (auto* fn = resolve(g_class, L"IsSpecificRumbleActive"))
    {
        dump_meta("IsSpecificRumbleActive", fn);
        out << "  IsSpecificRumbleActive(0, 0) = " << std::boolalpha << fn->call_native<bool>(g_context, 0.0f, 0.0f)
            << std::endl;
    }

    // Do object returns work at all?
    //
    // GetPlayer came back null in every round even with the world live and
    // engine time running, so it is not a timing artifact. These are other
    // zero-argument natives on the same class chain that should be non-null
    // in-world. If they return objects and GetPlayer alone does not, the return
    // mechanism is fine and GetPlayer is the outlier; if they are all null,
    // object returns do not work through call_native.
    for (const wchar_t* name : {L"GetWorld", L"GetHud", L"GetJournalManager", L"GetPlayer"})
    {
        auto* fn = resolve(g_class, name);
        if (!fn)
        {
            continue;
        }

        dump_meta(narrow(name, static_cast<std::uint32_t>(wcslen(name))).c_str(), fn);
        auto* object = fn->call_native<void*>(g_context);
        out << "  " << narrow(name, static_cast<std::uint32_t>(wcslen(name))) << "() = " << object << std::endl;
        if (object)
        {
            describe_object("    ", object);
        }
    }

    if (auto* fn = resolve(g_class, L"GetEngineTimeAsSeconds"))
    {
        out << "  GetEngineTimeAsSeconds() = " << fn->call_native<float>(g_context) << "  (post-check)" << std::endl;
    }
}

} // namespace

RED3LIB_C_EXPORT bool RED3LIB_CALL Main(HMODULE aHandle, EMainReason aReason)
{
    switch (aReason)
    {
    case EMainReason::Load:
    {
        open_log(aHandle);
        out << "RED3lib example loaded" << std::endl;
        break;
    }
    case EMainReason::Unload:
    {
        out << "RED3lib example unloading" << std::endl;
        g_log.close();
        break;
    }
    }

    return true;
}

RED3LIB_C_EXPORT void RED3LIB_CALL Update()
{
    // Sample repeatedly as the game progresses. The previous one-shot version
    // fired at the very first tick - long before the world exists - so every
    // native legitimately had nothing to return. Rounds spanning menu, load and
    // in-world distinguish "too early" from "marshalling is wrong".
    constexpr int frames_between_rounds = 300;
    constexpr int max_rounds = 4;
    constexpr int max_scans = 40;

    static int frame = 0;
    static int scans = 0;
    static int rounds = 0;
    static bool finished = false;

    if (finished)
    {
        return;
    }

    if (frame++ % frames_between_rounds != 0)
    {
        return;
    }

    if (!locate())
    {
        if (++scans > max_scans)
        {
            finished = true;
            out << "RED3lib: no CR4Game instance after " << max_scans << " scans, giving up" << std::endl;
        }
        return;
    }

    run_round(++rounds);

    if (rounds >= max_rounds)
    {
        finished = true;
        out << std::endl << "probes complete (" << rounds << " rounds)" << std::endl;
    }
}

RED3LIB_C_EXPORT const char* RED3LIB_CALL Supports()
{
    return supported_version;
}
