// Calls native script functions through the engine's dispatch table.
//
// This uses CFunction::call_native rather than CFunction::execute. execute()
// goes through CFunction::execute_native, whose address is not reachable from a
// name anchor and therefore goes stale on every game patch. call_native indexes
// the global native table with the CFunction's own registration_offset instead,
// and every address it needs can be regenerated by tools/w3offsets.
//
// Neither engine global this needs is hardcoded by hand:
//
//   * the CR4Game CClass comes from CR4GameClassBuilder's `cls` field, which
//     w3offsets locates through MSVC RTTI;
//   * the live CR4Game instance is found at runtime by scanning the image's
//     writable data for a pointer to an object whose vtable is CR4Game's
//     primary vtable - also RTTI-derived. See find_instance_slots().
//
// The probes are ordered to isolate failures: a primitive round trip first,
// then a String out, then a String in, then a multi-argument call, then the
// primitive again to confirm the stack survived.

#include <algorithm>
#include <cmath>
#include <initializer_list>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#include <Windows.h>

#include <red3lib/RED3lib.hpp>
#include <red3lib/detail/Addresses.hpp>
#include <red3lib/detail/Relocation.hpp>

#define RED3LIB_C_EXPORT extern "C" __declspec(dllexport)
#define RED3LIB_CALL __fastcall

enum class EMainReason : std::uint8_t
{
    Load = 0,
    Unload
};

namespace
{
// ---------------------------------------------------------------------------
// Regenerate with:  python tools/w3offsets/w3offsets.py --classes CR4Game
//
// Both values are name-anchored, so a game patch only means re-running the
// extractor. Neither was found by hand.
// ---------------------------------------------------------------------------
// RED3ext compares this against the numeric VS_FIXEDFILEINFO fields, which
// encode this build as 4.0.1.37654 even though its FileVersion string reads
// "4.0.0.103190" (103190 = 0x19316 overflows the 16-bit revision field).
constexpr const char* supported_version = "4.0.1.37654";

// CR4GameClassBuilder's instance + 0x8, i.e. IClassBuilder::cls. The builder's
// constructor zeroes exactly this address, which is what confirms the offset.
constexpr std::uintptr_t cr4game_class_offset = 0x145a82c70 - 0x140000000;

// CR4Game's primary vtable: the complete-object locator whose subobject offset
// is 0. CR4Game uses multiple inheritance, so its other three vtables are the
// wrong fingerprint for identifying an instance.
constexpr std::uintptr_t cr4game_vtable_offset = 0x142d0ee38 - 0x140000000;

std::string narrow(const wchar_t* text, std::uint32_t length)
{
    if (!text || length == 0)
    {
        return {};
    }

    auto needed = WideCharToMultiByte(CP_UTF8, 0, text, static_cast<int>(length), nullptr, 0, nullptr, nullptr);
    if (needed <= 0)
    {
        return {};
    }

    std::string out(static_cast<std::size_t>(needed), '\0');
    WideCharToMultiByte(CP_UTF8, 0, text, static_cast<int>(length), out.data(), needed, nullptr, nullptr);
    return out;
}

// Probe output goes to a file next to the plugin as well as to stdout: a game
// process has no console unless RED3ext's dev console is enabled, and even then
// the window cannot be read back afterwards. Every line is flushed so a crash
// mid-probe still leaves the results on disk.
std::ofstream g_log;

struct Tee
{
    template<typename T>
    Tee& operator<<(const T& value)
    {
        std::cout << value;
        if (g_log)
            g_log << value;
        return *this;
    }

    Tee& operator<<(std::ostream& (*manip)(std::ostream&))
    {
        std::cout << manip;
        if (g_log)
            g_log << manip;
        return *this;
    }

    Tee& operator<<(std::ios_base& (*manip)(std::ios_base&))
    {
        std::cout << manip;
        if (g_log)
            g_log << manip;
        return *this;
    }
};

Tee out;

void open_log(HMODULE self)
{
    wchar_t path[MAX_PATH]{};
    if (GetModuleFileNameW(self, path, MAX_PATH) == 0)
    {
        return;
    }

    std::filesystem::path file = path;
    file.replace_filename(L"probes.log");
    g_log.open(file, std::ios::out | std::ios::trunc);
}

// A committed, readable span of the address space.
struct Region
{
    const std::uint8_t* begin;
    const std::uint8_t* end;
};

// Snapshot every readable region once, then answer readability by binary search.
// The previous version called VirtualQuery per candidate pointer with a
// one-entry cache; candidates alternate between regions often enough that the
// cache thrashed, and the whole scan then ran again on the next frame. That is
// tens of thousands of syscalls per frame on the game's main thread, which
// presents as a hang rather than a stutter.
std::vector<Region> snapshot_readable_regions()
{
    constexpr DWORD readable = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READ |
                               PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;

    SYSTEM_INFO si{};
    GetSystemInfo(&si);

    std::vector<Region> regions;
    auto* cursor = static_cast<const std::uint8_t*>(si.lpMinimumApplicationAddress);
    const auto* limit = static_cast<const std::uint8_t*>(si.lpMaximumApplicationAddress);

    MEMORY_BASIC_INFORMATION info{};
    while (cursor < limit && VirtualQuery(cursor, &info, sizeof(info)) == sizeof(info))
    {
        const auto* base = static_cast<const std::uint8_t*>(info.BaseAddress);
        if (info.State == MEM_COMMIT && (info.Protect & readable) != 0 && (info.Protect & PAGE_GUARD) == 0)
        {
            regions.push_back({base, base + info.RegionSize});
        }

        auto* next = base + info.RegionSize;
        if (next <= cursor)
        {
            break;
        }
        cursor = next;
    }

    return regions;
}

bool is_readable(const std::vector<Region>& regions, const void* address, std::size_t size)
{
    const auto* p = static_cast<const std::uint8_t*>(address);
    auto it = std::upper_bound(regions.begin(), regions.end(), p,
                               [](const std::uint8_t* v, const Region& r) { return v < r.begin; });
    if (it == regions.begin())
    {
        return false;
    }

    --it;
    return p >= it->begin && p + size <= it->end;
}

// Find globals holding a pointer to an instance of the class owning `vtable`.
//
// A singleton like GGame is a plain data global, written once through the
// engine's generic RTTI create-object path, so nothing about its call site
// identifies it statically. Its contents are identifiable though: the object it
// points at begins with a vtable pointer, and that vtable is reachable by name
// through RTTI. Scanning for the relationship finds the global on any build.
std::vector<void**> find_instance_slots(const void* vtable, std::size_t limit)
{
    std::vector<void**> found;

    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandle(nullptr));
    if (!base)
    {
        return found;
    }

    auto* dos = reinterpret_cast<IMAGE_DOS_HEADER*>(base);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE)
    {
        return found;
    }

    auto* nt = reinterpret_cast<IMAGE_NT_HEADERS*>(base + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE)
    {
        return found;
    }

    const auto regions = snapshot_readable_regions();

    auto* section = IMAGE_FIRST_SECTION(nt);
    auto section_count = static_cast<std::size_t>(nt->FileHeader.NumberOfSections);

    for (std::size_t i = 0; i < section_count; i++, section++)
    {
        // Writable and not executable: where a singleton pointer would live.
        if ((section->Characteristics & IMAGE_SCN_MEM_WRITE) == 0)
        {
            continue;
        }

        if ((section->Characteristics & IMAGE_SCN_MEM_EXECUTE) != 0)
        {
            continue;
        }

        auto* slots = reinterpret_cast<void**>(base + section->VirtualAddress);
        auto count = static_cast<std::size_t>(section->Misc.VirtualSize) / sizeof(void*);
        if (count == 0 || !is_readable(regions, slots, sizeof(void*)))
        {
            continue;
        }

        for (std::size_t k = 0; k < count; k++)
        {
            auto* candidate = slots[k];
            if (!candidate || (reinterpret_cast<std::uintptr_t>(candidate) & 7u) != 0)
            {
                continue;
            }

            if (!is_readable(regions, candidate, sizeof(void*)))
            {
                continue;
            }

            if (*reinterpret_cast<void* const*>(candidate) != vtable)
            {
                continue;
            }

            found.push_back(&slots[k]);
            if (found.size() >= limit)
            {
                return found;
            }
        }
    }

    return found;
}

// Primary vtables, RTTI-derived (python w3offsets.py --classes CR4Player ...).
// An object's vptr names its most-derived NATIVE class - a script class such as
// W3PlayerWitcher is instantiated on its nearest native base and carries that
// base's vptr, so CR4Player is what a player object reports.
struct known_class
{
    const char* name;
    std::uintptr_t vtable_offset;
};

constexpr known_class known_classes[] = {
    {"CR4Player", 0x2d71520}, {"CPlayer", 0x2b3fea8}, {"CNewNPC", 0x2b4bd68},
    {"CActor", 0x2b3ce38},    {"CEntity", 0x2a211a8}, {"CR4Game", 0x2d0ee38},
};

// A returned pointer is engine-controlled and might be a handle, a null, or
// something unmapped - check before dereferencing it.
bool readable(const void* address, std::size_t size)
{
    MEMORY_BASIC_INFORMATION info{};
    if (VirtualQuery(address, &info, sizeof(info)) == 0)
    {
        return false;
    }

    constexpr DWORD ok = PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE |
                         PAGE_EXECUTE_WRITECOPY;
    if (info.State != MEM_COMMIT || (info.Protect & ok) == 0 || (info.Protect & PAGE_GUARD) != 0)
    {
        return false;
    }

    const auto* begin = static_cast<const std::uint8_t*>(info.BaseAddress);
    return static_cast<const std::uint8_t*>(address) + size <= begin + info.RegionSize;
}

// Report what an engine-returned object actually is, using the CEntity field
// offsets the RTTI dump gives us.
void describe_object(const char* indent, void* object)
{
    if (!object || !readable(object, 512))
    {
        out << indent << "not a readable object" << std::endl;
        return;
    }

    auto* cls = red3lib::class_of(object);
    if (!cls || !readable(cls, sizeof(red3lib::CClass)))
    {
        out << indent << "no readable CClass at +0x18" << std::endl;
        return;
    }

    auto class_name = cls->name.to_wide();
    out << indent << "class = " << narrow(class_name.data(), static_cast<std::uint32_t>(class_name.size()))
        << "  size = " << cls->size << std::endl;

    // The GUID and tag list are at CEntity's offsets, so they only mean
    // anything if this object really is an entity. They used to be read off
    // every object, which is why a journal manager reported a tag count.
    bool is_entity = false;
    for (auto* c = cls; c; c = c->base)
    {
        if (c->name == red3lib::CNameHash(L"CEntity"))
        {
            is_entity = true;
            break;
        }
    }

    if (!is_entity)
    {
        out << indent << "not a CEntity, so no GUID or tags to read" << std::endl;
        return;
    }

    auto* bytes = reinterpret_cast<std::uint8_t*>(object);
    bool guid_set = false;
    for (int i = 0; i < 16; i++)
    {
        if (bytes[204 + i])
        {
            guid_set = true;
        }
    }

    const auto& tags = *reinterpret_cast<red3lib::TDynArray<void*>*>(bytes + 192);
    out << indent << "guid set = " << std::boolalpha << guid_set << ", tags = { entries "
        << static_cast<const void*>(tags.entries) << ", count " << tags.size << " }" << std::endl;
}

// Dump the raw 12 bytes as well as the decoded text. The byte view is the point
// of the exercise: it shows the field order directly, and whether "size"
// includes the terminating null.
void dump_string(const char* label, const red3lib::String& value)
{
    out << "  " << label << " raw =";

    const auto* raw = reinterpret_cast<const std::uint8_t*>(&value);
    for (std::size_t i = 0; i < sizeof(red3lib::String); i++)
    {
        out << ' ' << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(raw[i]);
    }

    out << std::dec << "\n    data = " << static_cast<const void*>(value.data) << ", size = " << value.size
        << ", text = \"" << narrow(value.data, value.size) << "\"" << std::endl;
}

red3lib::CFunction* resolve(red3lib::CClass* cls, const wchar_t* name)
{
    auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));

    auto function = cls->find_function(name);
    if (!function)
    {
        out << "  [skip] " << narrowed << " not found on the class chain" << std::endl;
        return nullptr;
    }

    if (!function->is_native())
    {
        out << "  [skip] " << narrowed << " is scripted, not native" << std::endl;
        return nullptr;
    }

    return function;
}

// Returns false while the game object does not exist yet, so Update() retries.
// Per-function metadata. If registration_offset is nonsense, or impl does not
// land in the game's .text, then call_native is dispatching to the wrong entry
// and no amount of stack-frame fiddling will help.
void dump_meta(const char* label, red3lib::CFunction* fn)
{
    const void* impl = nullptr;
    if (fn->registration_offset >= 0)
    {
        const auto index = static_cast<std::size_t>(fn->registration_offset);
        if (fn->is_global())
        {
            red3lib::detail::RelocArray<red3lib::CFunction::native_fn_t> table(
                red3lib::detail::addresses::CFunction::native_table);
            impl = reinterpret_cast<const void*>(table[index]);
        }
        else
        {
            red3lib::detail::RelocArray<red3lib::CFunction::native_method_entry> table(
                red3lib::detail::addresses::CFunction::class_method_table);
            impl = reinterpret_cast<const void*>(table[index].code);
        }
    }

    out << "    [" << label << "] flags=0x" << std::hex << fn->flags << std::dec << " params=" << fn->params.size
        << " locals=" << fn->locals.size << " stackSize=" << fn->stack_size << " regOffset=" << fn->registration_offset
        << " impl=" << impl << std::endl;
}

// The engine's Vector - four floats, 16 bytes, per the RTTI dump. A native
// writes its result through the third argument, so only the size has to match.
struct engine_vector
{
    float x;
    float y;
    float z;
    float w;
};

// A function's real signature. The RTTI dump records neither parameters nor
// return types - both exist only at runtime, on the CProperty entries. The type
// name comes from IRTTIType vtable slot 1, which returns a POINTER to the name.
std::string type_name_of(red3lib::CProperty* property)
{
    if (!property || !property->type)
    {
        return "<none>";
    }

    const auto* name = property->type->name();
    if (!name)
    {
        return "<unnamed>";
    }

    auto wide = name->to_wide();
    return wide.empty() ? std::string("<empty>") : narrow(wide.data(), static_cast<std::uint32_t>(wide.size()));
}

void dump_signature(const char* indent, const char* label, red3lib::CFunction* fn)
{
    out << indent << label << "(";

    for (std::uint32_t i = 0; i < fn->params.size; i++)
    {
        if (i)
        {
            out << ", ";
        }

        auto* property = fn->params.entries[i];
        out << type_name_of(property);
        if (property)
        {
            out << " @" << property->offset;
        }
    }

    out << ") -> " << (fn->return_property ? type_name_of(fn->return_property) : std::string("void"))
        << "   [stackSize=" << fn->stack_size << ", size=" << (fn->return_property && fn->return_property->type
                                                                   ? fn->return_property->type->size()
                                                                   : 0)
        << "]" << std::endl;
}

// Every function a class offers, including the scripted ones the RTTI dump
// cannot show, with the signature read off each CFunction.
void dump_class_functions(const char* indent, red3lib::CClass* cls, int max_classes)
{
    int depth = 0;
    for (auto* c = cls; c && depth < max_classes; c = c->base, depth++)
    {
        auto class_name = c->name.to_wide();
        out << indent << narrow(class_name.data(), static_cast<std::uint32_t>(class_name.size())) << "  ("
            << c->functions.size << " functions)" << std::endl;

        for (std::uint32_t i = 0; i < c->functions.size; i++)
        {
            auto* fn = c->functions.entries[i];
            if (!fn)
            {
                continue;
            }

            auto fn_name = fn->name.to_wide();
            auto narrowed = narrow(fn_name.data(), static_cast<std::uint32_t>(fn_name.size()));
            out << indent << "  " << (fn->is_native() ? "native  " : "scripted ");
            dump_signature("", narrowed.c_str(), fn);
        }
    }
}

red3lib::CClass* g_class = nullptr;
red3lib::IScriptable* g_context = nullptr;

// Locate the class and the live instance. Cached: the address-space scan is
// expensive and must not be repeated once it has succeeded.
bool locate()
{
    if (g_class && g_context)
    {
        return true;
    }

    red3lib::detail::RelocPtr<red3lib::CClass> game_class(cr4game_class_offset);
    if (game_class == nullptr)
    {
        return false;
    }

    red3lib::detail::RelocArray<std::uint8_t> vtable(cr4game_vtable_offset);
    auto slots = find_instance_slots(vtable.data(), 8);
    if (slots.empty())
    {
        return false;
    }

    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandle(nullptr));
    g_class = game_class.get();
    g_context = static_cast<red3lib::IScriptable*>(*slots.front());

    out << "located CR4Game\n"
        << "  CClass   = " << static_cast<const void*>(g_class) << "\n"
        << "  vtable   = " << static_cast<const void*>(vtable.data()) << "\n"
        << "  instance = " << static_cast<const void*>(g_context) << " via " << slots.size() << " global(s)"
        << std::endl;
    for (auto* slot : slots)
    {
        out << "    +0x" << std::hex << static_cast<std::size_t>(reinterpret_cast<std::uint8_t*>(slot) - base)
            << std::dec << std::endl;
    }
    return true;
}

// Put words on screen, with the given entity as the speaker.
//
// ShowOneliner is the floating line above an actor's head - what the game uses
// for its own barks. The first attempt made the PLAYER the speaker and nothing
// appeared; OnCreateOneliner takes the entity as the one talking, so the player
// is probably not a case the HUD renders. An NPC is the game's own usage.
//
// The richer channels - OnDialogSentenceSet, OnSubtitleAdded - are scripted, so
// call_native refuses them while execute_scripted is stale. Going through the
// native entry lets the engine dispatch into them.
void speak_oneliner(red3lib::Handle<void>& speaker, const std::string& who, float distance)
{
    auto* fn = resolve(g_class, L"GetHud");
    if (!fn)
    {
        return;
    }

    red3lib::owned<red3lib::Handle<void>> hud(fn->return_type(),
                                             fn->call_native<red3lib::Handle<void>>(g_context));
    auto* hud_class = hud->get() ? red3lib::class_of(hud->get()) : nullptr;
    if (!hud_class)
    {
        out << "    no HUD to speak through" << std::endl;
        return;
    }

    auto* method = hud_class->find_function(L"ShowOneliner");
    const bool callable = method && method->is_native() && method->params.size == 2 && method->param_type(0) &&
                          method->param_type(1) && method->param_type(0)->size() == sizeof(red3lib::String) &&
                          method->param_type(1)->size() == sizeof(red3lib::Handle<void>);

    if (!callable)
    {
        out << "    ShowOneliner is not callable with what we have" << std::endl;
        return;
    }

    static wchar_t line[] = L"RED3lib speaking.";
    method->call_native<void>(reinterpret_cast<red3lib::IScriptable*>(hud->get()), red3lib::borrow_string(line),
                              speaker);

    out << "    ShowOneliner -> " << who << " at " << distance << "m" << std::endl;
}

// Where does a CProperty keep its name?
//
// The layout has type@0x08, offset@0x20 and flags@0x24, with 0x10 and 0x18
// unidentified. Rather than guess, resolve each candidate dword as a name index
// and see which one produces the property names we already know from the dump -
// CR4Game has `player` and `activeWorld`.
void find_property_name_offset(red3lib::CClass* cls)
{
    out << "  CProperty name offset probe (expecting player / activeWorld):" << std::endl;

    for (std::uint32_t i = 0; i < cls->properties.size && i < 4; i++)
    {
        auto* property = cls->properties.entries[i];
        if (!property || !readable(property, 0x30))
        {
            continue;
        }

        out << "    property " << i << " offset=" << property->offset << ":";

        const auto* raw = reinterpret_cast<const std::uint8_t*>(property);
        for (std::uint32_t at : {0x10u, 0x14u, 0x18u, 0x1Cu})
        {
            red3lib::CNameHash candidate{};
            std::memcpy(&candidate, raw + at, sizeof(candidate));
            auto text = candidate.to_wide();

            out << "  +0x" << std::hex << at << std::dec << "=";
            if (text.empty())
            {
                out << "<none>";
            }
            else
            {
                out << narrow(text.data(), static_cast<std::uint32_t>(text.size()));
            }
        }

        out << std::endl;
    }
}

// The control that has been missing: is a HANDLE argument delivered?
//
// String arguments are proven by Pause / IsPausedForReason. Handles are not, and
// ShowOneliner tolerates a null entity - it dispatches anyway - so an argument
// that never arrives is indistinguishable from a call that did nothing.
//
// The first attempt tested ONE function, IsDangerous, and got 0 for a real
// handle, a null handle and a different handle. That proves nothing: false is a
// perfectly good answer for all three. Betting on a single function was the
// mistake, so this tries every candidate of the right SHAPE - one handle
// parameter, non-void return, a read-only name - until one of them answers
// differently. Only a DIFFERENCE is evidence; identical results stay silent.
//
// Each name is logged and flushed BEFORE the call, so if one of these natives
// takes the game down, the log names it.
void probe_handle_argument(red3lib::CClass* cls, red3lib::IScriptable* context, red3lib::Handle<void>& subject,
                           red3lib::Handle<void>& other)
{
    int tried = 0;
    bool discriminated = false;

    for (auto* c = cls; c && tried < 14; c = c->base)
    {
        for (std::uint32_t i = 0; i < c->functions.size && tried < 14; i++)
        {
            auto* fn = c->functions.entries[i];
            if (!fn || !fn->is_native() || fn->params.size != 1 || !fn->return_property)
            {
                continue;
            }

            auto* param = fn->param_type(0);
            auto* returns = fn->return_property->type;
            if (!param || !returns || param->size() != sizeof(red3lib::Handle<void>) ||
                returns->size() > sizeof(std::uint64_t))
            {
                continue;
            }

            const auto* param_name = param->name();
            if (!param_name || param_name->to_wide().rfind(L"handle:", 0) != 0)
            {
                continue;
            }

            auto fn_text = fn->name.to_wide();
            if (fn_text.rfind(L"Get", 0) != 0 && fn_text.rfind(L"Is", 0) != 0 && fn_text.rfind(L"Has", 0) != 0 &&
                fn_text.rfind(L"Can", 0) != 0)
            {
                continue;
            }

            tried++;

            auto narrowed = narrow(fn_text.data(), static_cast<std::uint32_t>(fn_text.size()));
            out << "    trying " << narrowed << " ..." << std::endl;

            red3lib::Handle<void> nothing{};
            const auto a = fn->call_native<std::uint64_t>(context, subject);
            const auto b = fn->call_native<std::uint64_t>(context, nothing);
            const auto d = fn->call_native<std::uint64_t>(context, other);

            const bool differs = a != b || d != b;
            discriminated = discriminated || differs;

            out << "      subject=0x" << std::hex << a << "  null=0x" << b << "  other=0x" << d << std::dec
                << (differs ? "   <-- DIFFERS, the handle IS delivered" : "   (identical)") << std::endl;

            if (differs)
            {
                return;
            }
        }
    }

    out << "    tried " << tried << " candidates, none discriminated - handle delivery still unproven"
        << std::endl;
    (void)discriminated;
}

// Is a SECOND argument delivered? Settled with a signature we already know.
//
// Scanning for a function of the right shape found none - actors have no native
// taking a small first argument and a handle second - so this stops hunting and
// uses GetNPCsByTag(CName @0, array @4), whose signature was read from the live
// CFunction earlier.
//
// It discriminates by construction. Called with a tag an NPC really carries it
// must return entries; called with a tag nothing carries it must return none.
// Filling the array at offset 4 also means the ENGINE located a second
// parameter's offset, which is the same mechanism ShowOneliner needs to find its
// entity at offset 16.
void probe_second_argument(red3lib::IScriptable* game, red3lib::Handle<void>& npc)
{
    auto* by_tag = resolve(g_class, L"GetNPCsByTag");
    if (!by_tag || by_tag->params.size != 2)
    {
        out << "    GetNPCsByTag unavailable" << std::endl;
        return;
    }

    auto* npc_class = red3lib::class_of(npc.get());
    auto* tags_fn = npc_class ? npc_class->find_function(L"GetTagsString") : nullptr;
    if (!tags_fn || !tags_fn->is_native())
    {
        out << "    cannot read the NPC's tags" << std::endl;
        return;
    }

    red3lib::owned<red3lib::String> tags(tags_fn->return_type(),
                                        tags_fn->call_native<red3lib::String>(
                                            reinterpret_cast<red3lib::IScriptable*>(npc.get())));
    if (!tags->data)
    {
        out << "    the NPC has no tags to search by" << std::endl;
        return;
    }

    // Tags print as "[ ONE; TWO ]" - take the first.
    std::wstring first;
    for (std::uint32_t i = 0; i < tags->size && tags->data[i]; i++)
    {
        const auto ch = tags->data[i];
        const bool word = (ch >= L'A' && ch <= L'Z') || (ch >= L'a' && ch <= L'z') || (ch >= L'0' && ch <= L'9') ||
                          ch == L'_';
        if (word)
        {
            first.push_back(ch);
        }
        else if (!first.empty())
        {
            break;
        }
    }

    if (first.empty())
    {
        out << "    no usable tag in " << narrow(tags->data, tags->size ? tags->size - 1 : 0) << std::endl;
        return;
    }

    out << "    tag = " << narrow(first.c_str(), static_cast<std::uint32_t>(first.size())) << std::endl;

    auto run = [&](const wchar_t* text, const char* label)
    {
        red3lib::CNameHash name(text);
        red3lib::TDynArray<red3lib::Handle<void>> found{};

        // Logged and flushed BEFORE the call. This exact call took the game down
        // when the second argument was being dropped, so if anything is still
        // wrong the log says how far it got.
        out << "      calling GetNPCsByTag with " << label << " ..." << std::endl;

        by_tag->call_native<void>(game, name, found);

        out << "      " << label << " -> " << found.size << " NPC(s)" << std::endl;

        const auto count = found.size;
        if (auto* type = by_tag->param_type(1))
        {
            type->destruct(&found);
        }

        return count;
    };

    const auto real = run(first.c_str(), "real tag      ");
    const auto bogus = run(L"RED3LIB_NO_SUCH_TAG", "nonsense tag  ");

    out << "      " << (real > 0 && bogus == 0 ? "the SECOND argument IS delivered"
                                               : "inconclusive - both answers are the same")
        << std::endl;
}

// One round of probes. Repeated as the game progresses: values that are zero at
// the menu but populated in-world tell us the earlier run was simply too early,
// rather than the marshalling being wrong.
void run_round(int round)
{
    out << "\n--- round " << round << " ---" << std::endl;

    // Do nothing at all until a world is loaded.
    //
    // Everything below is diagnostics, and running it during startup - while the
    // intro video plays and the engine is still assembling itself - is risk with
    // no benefit, because the answers it produces there are already known. Two
    // abnormal terminations happened in exactly that window, with the player
    // null in every round of both. That is not proof the plugin caused them, but
    // there is nothing here worth doing before the world exists.
    {
        auto& player_handle = *reinterpret_cast<red3lib::Handle<void>*>(
            reinterpret_cast<std::uint8_t*>(g_context) + 48592);

        if (!player_handle.get())
        {
            out << "  round " << round << ": no world yet, staying out of the way" << std::endl;
            return;
        }
    }

    // "First" now means the first round WITH a world, not the first tick.
    // Anything that cannot change between rounds runs once; the rounds exist to
    // watch live state, not to repeat settled proofs.
    static bool done_static = false;
    const bool first = !done_static;
    done_static = true;

    if (auto* fn = resolve(g_class, L"GetEngineTimeAsSeconds"))
    {
        dump_meta("GetEngineTimeAsSeconds", fn);
        out << "  GetEngineTimeAsSeconds() = " << fn->call_native<float>(g_context) << std::endl;
    }

    if (auto* fn = first ? resolve(g_class, L"GetApplicationVersion") : nullptr)
    {
        dump_meta("GetApplicationVersion", fn);
        red3lib::owned<red3lib::String> version(fn->return_type(), fn->call_native<red3lib::String>(g_context));
        dump_string("GetApplicationVersion() ->", *version);
    }

    // A one-argument call. String arguments are deliberately not probed: they
    // are 12 bytes and the VM has no immediate opcode for that width, so
    // CStackFrameCodeWriter rejects them at compile time rather than letting the
    // call corrupt the code stream. GetTimeScale takes a bool, which encodes as
    // a 1-byte immediate.
    if (auto* fn = first ? resolve(g_class, L"GetTimeScale") : nullptr)
    {
        dump_meta("GetTimeScale", fn);
        out << "  GetTimeScale(true) = " << fn->call_native<float>(g_context, true) << std::endl;
    }

    // The Pause / IsPausedForReason / Unpause sequence used to run here. It
    // proved String argument delivery - Pause keys on the string, so setting the
    // state and reading it back could only agree if the content survived - and
    // that question is settled.
    //
    // It has been REMOVED rather than left in. It is the only probe that mutates
    // game state, round 1 now lands during startup while the intro video plays,
    // and pausing the game at that moment is risk with no remaining information
    // to gain. Two abnormal terminations have happened around this point; that
    // is not proof it was the cause, but a mutation that teaches us nothing is
    // not worth defending.

    if (auto* fn = first ? resolve(g_class, L"IsSpecificRumbleActive") : nullptr)
    {
        dump_meta("IsSpecificRumbleActive", fn);
        out << "  IsSpecificRumbleActive(0, 0) = " << std::boolalpha << fn->call_native<bool>(g_context, 0.0f, 0.0f)
            << std::endl;
    }

    // Object returns, dereferenced properly.
    //
    // Natives whose RTTI return type is CRTTIHandleType return a HANDLE - eight
    // bytes pointing at a control block, with the object at +0x08 - not a raw
    // object pointer. Reading the handle as an object reads its refcount as a
    // vptr, which is what made these look broken.
    //
    // GetPlayer is deliberately absent: its return property is null, so RTTI
    // says it returns nothing. It was only ever probed because the name implied
    // an accessor.
    for (const wchar_t* name : {L"GetWorld", L"GetHud", L"GetJournalManager"})
    {
        auto* fn = resolve(g_class, name);
        if (!fn)
        {
            continue;
        }

        auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));
        dump_meta(narrowed.c_str(), fn);

        red3lib::owned<red3lib::Handle<void>> handle(fn->return_type(),
                                                     fn->call_native<red3lib::Handle<void>>(g_context));
        out << "  " << narrowed << "() handle = " << static_cast<const void*>(handle->block)
            << "  object = " << static_cast<const void*>(handle->get()) << std::endl;
        if (*handle)
        {
            describe_object("    ", handle->get());
        }
    }

    // Calling a method on an object we did not start with.
    //
    // Every call so far has used the game's own class and instance. This takes
    // the journal manager handle, reads its CClass from the object itself, and
    // resolves and calls one of ITS methods - which is what makes the whole
    // object graph reachable rather than just the game object.
    if (auto* fn = first ? resolve(g_class, L"GetJournalManager") : nullptr)
    {
        auto handle = fn->call_native<red3lib::Handle<void>>(g_context);
        auto* object = handle.get();
        auto* cls = red3lib::class_of(object);
        auto* block = handle.block;

        out << "  journal manager = " << static_cast<const void*>(object)
            << "  its CClass = " << static_cast<const void*>(cls) << std::endl;

        if (cls)
        {
            out << "    class size = " << cls->size << ", scripted size = " << cls->scripted_size << std::endl;

            if (auto* method = cls->find_function(L"GetRegularQuestCount"))
            {
                out << "    resolved GetRegularQuestCount on its own class, native = " << std::boolalpha
                    << method->is_native() << std::endl;
                auto count = method->call_native<std::int32_t>(reinterpret_cast<red3lib::IScriptable*>(object));
                out << "    GetRegularQuestCount() = " << count << std::endl;
            }
            else
            {
                out << "    GetRegularQuestCount not found - class_of returned the wrong class" << std::endl;
            }
        }

        // Does releasing actually release? The control block keeps a 32-bit
        // refcount at +0x00, so this is readable rather than inferred.
        //
        // Only checked when the count is above 1 to begin with: at 1, destruct
        // drops it to zero and frees the block, and reading it afterwards would
        // be a use-after-free.
        if (block)
        {
            const auto before = block->references;
            auto* type = fn->return_type();

            if (type && before > 1)
            {
                type->destruct(&handle);
                out << "    handle refcount " << before << " -> " << block->references << " after destruct"
                    << (block->references == before - 1 ? "  (released)" : "  (NOT RELEASED)") << std::endl;
            }
            else
            {
                out << "    handle refcount = " << before << ", not releasing (would free the block)" << std::endl;
            }
        }
    }

    // What do the enumeration natives actually take? The dump cannot say, so
    // read it off the live CFunction.
    //
    // GetTimeScale and IsPausedForReason are controls: their parameter types
    // are already known to be Bool and String, so if those two print correctly
    // the rest of the reading can be trusted.
    if (first)
    {
        out << "  signatures:" << std::endl;
        for (const wchar_t* name : {L"GetTimeScale", L"IsPausedForReason", L"GetAllNPCs", L"GetNPCsByTag",
                                    L"GetNPCByTag", L"GetJournalManager"})
        {
            if (auto* fn = resolve(g_class, name))
            {
                auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));
                dump_signature("    ", narrowed.c_str(), fn);
            }
        }
    }

    // Is a HANDLE argument delivered at all?
    //
    // String arguments are proven, by Pause / IsPausedForReason. A handle
    // argument has never been checked, and ShowOneliner tolerates a null entity
    // - it dispatches anyway - so a handle that never arrives looks exactly
    // like a call that did nothing. This is the missing control.
    if (first)
    {
        find_property_name_offset(g_class);

        for (const wchar_t* name : {L"RequestPopup", L"ClosePopup", L"EnableSubtitles", L"AreSubtitlesEnabled"})
        {
            if (auto* fn = resolve(g_class, name))
            {
                auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));
                dump_signature("    ", narrowed.c_str(), fn);
            }
        }
    }

    // Text output: what can actually put words on screen.
    //
    // GetHud returns null at the main menu, which is why earlier rounds saw
    // nothing - with a world loaded it hands back a CR4ScriptedHud. CR4Hud
    // declares ShowOneliner natively, which is the floating line above an
    // actor's head. The scripted subclass may offer more, and scripted methods
    // are invisible to the RTTI dump, so this lists what the live class really
    // has rather than what the dump knows.
    if (auto* fn = resolve(g_class, L"GetHud"))
    {
        red3lib::owned<red3lib::Handle<void>> hud(fn->return_type(),
                                                 fn->call_native<red3lib::Handle<void>>(g_context));

        auto* hud_class = hud->get() ? red3lib::class_of(hud->get()) : nullptr;

        static bool dumped_hud = false;
        if (hud_class && !dumped_hud)
        {
            dumped_hud = true;

            out << "  HUD class functions:" << std::endl;
            dump_class_functions("    ", hud_class, 3);

            if (auto* method = hud_class->find_function(L"ShowOneliner"))
            {
                out << "  ShowOneliner found, native = " << std::boolalpha << method->is_native() << std::endl;
                dump_signature("    ", "ShowOneliner", method);
            }

            // Calling a SCRIPTED function.
            //
            // Everything called so far has been native. CR4ScriptedHud carries
            // 104 scripted functions against the dump's 4, and the game's logic
            // lives in classes like this, so reaching them roughly doubles what
            // is callable.
            //
            // Safest first, each logged and flushed before the call.
            auto* hud_self = reinterpret_cast<red3lib::IScriptable*>(hud->get());

            if (auto* method = hud_class->find_function(L"IsHudVisibilityAllowedByUser"))
            {
                if (!method->is_native() && method->params.size == 0)
                {
                    out << "  calling SCRIPTED IsHudVisibilityAllowedByUser ..." << std::endl;
                    const auto allowed = method->call_scripted<bool>(hud_self);
                    out << "    -> " << std::boolalpha << allowed << std::endl;
                }
            }

            // Discriminating: a scripted function whose result must vary with
            // its arguments. Equal outputs for different inputs would mean the
            // arguments are not arriving, the same trap the native path had.
            if (auto* method = hud_class->find_function(L"GetScaleformPoint"))
            {
                if (!method->is_native() && method->params.size == 2)
                {
                    out << "  calling SCRIPTED GetScaleformPoint ..." << std::endl;
                    const auto origin = method->call_scripted<engine_vector>(hud_self, 0.0f, 0.0f);
                    const auto offset = method->call_scripted<engine_vector>(hud_self, 100.0f, 200.0f);

                    const bool differs = origin.x != offset.x || origin.y != offset.y;
                    out << "    (0,0) -> " << origin.x << ", " << origin.y << "   (100,200) -> " << offset.x << ", "
                        << offset.y << (differs ? "   <-- DIFFERS, scripted arguments delivered" : "   (identical)")
                        << std::endl;
                }
            }
        }

        // The call itself happens in the enumeration below, where an NPC handle
        // is available. Targeting the player produced no visible text.
    }

    // The player, and reading state off it.
    //
    // CR4Game declares `player` as `handle:CPlayer` at offset 48592, so the
    // player is a plain field read off the game instance we already have - no
    // tag to guess and no heap scan. The offset comes from the game's own
    // -dumprtti, so a patch means regenerating it rather than re-finding it.
    //
    // The class chain is what makes this discriminating. A stray pointer can
    // still yield a plausible-looking class, but it will not reproduce the
    // exact inheritance AND the per-level sizes that the RTTI dump records
    // independently. Names are compared as interned CNameHash indices rather
    // than resolved to text as well as printed: interning makes equal names
    // equal indices, so the check does not depend on the pool lookup being
    // right.
    {
        constexpr std::size_t player_field_offset = 48592;

        static const struct
        {
            const wchar_t* name;
            std::int32_t size;
        } expected[] = {
            {L"CR4Player", 2752}, {L"CPlayer", 2496},          {L"CActor", 2368},
            {L"CGameplayEntity", 512}, {L"CPeristentEntity", 400}, {L"CEntity", 368},
            {L"CNode", 240},      {L"CObject", 88},            {L"IScriptable", 48},
            {L"ISerializable", 16}, {L"IReferencable", 16},
        };

        auto& handle = *reinterpret_cast<red3lib::Handle<void>*>(
            reinterpret_cast<std::uint8_t*>(g_context) + player_field_offset);
        auto* player = handle.get();

        out << std::endl
            << "  CR4Game.player handle = " << static_cast<const void*>(handle.block)
            << "  object = " << static_cast<const void*>(player) << std::endl;

        if (!player)
        {
            out << "    null - no player in the world yet" << std::endl;
        }
        else
        {
            out << "    class chain:" << std::endl;

            int depth = 0;
            for (auto* c = red3lib::class_of(player); c && depth < 24; c = c->base, depth++)
            {
                auto class_name = c->name.to_wide();
                out << "      [" << depth << "] "
                    << (class_name.empty()
                            ? std::string("<unnamed>")
                            : narrow(class_name.data(), static_cast<std::uint32_t>(class_name.size())))
                    << "  size=" << c->size;

                const wchar_t* matched = nullptr;
                std::int32_t dump_size = 0;
                for (const auto& entry : expected)
                {
                    if (c->name == red3lib::CNameHash(entry.name))
                    {
                        matched = entry.name;
                        dump_size = entry.size;
                        break;
                    }
                }

                if (!matched)
                {
                    // Not a failure on its own: the runtime class may be a
                    // scripted subclass, which the native dump does not list.
                    out << "  <not a native class - scripted, so absent from the dump>";
                }
                else
                {
                    out << (c->size == dump_size ? "  size agrees with the dump"
                                                 : "  SIZE DISAGREES WITH THE DUMP");
                }

                out << std::endl;
            }

            auto* cls = red3lib::class_of(player);
            auto* self = reinterpret_cast<red3lib::IScriptable*>(player);

            // Each of these returns an engine-allocated String that nothing here
            // frees, so they run once rather than every round.
            static bool described_player = false;
            const bool describe_now = !described_player;
            described_player = true;

            const std::initializer_list<const wchar_t*> none{};
            const std::initializer_list<const wchar_t*> names{L"GetName", L"GetDisplayName", L"GetTagsString"};

            for (const wchar_t* name : describe_now ? names : none)
            {
                auto* method = resolve(cls, name);
                if (!method)
                {
                    continue;
                }

                auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));
                red3lib::owned<red3lib::String> text(method->return_type(),
                                                    method->call_native<red3lib::String>(self));

                if (!text->data)
                {
                    out << "    " << narrowed << "() = <null string>" << std::endl;
                    continue;
                }

                // size counts the terminator, so trim it for display.
                out << "    " << narrowed << "() = \"" << narrow(text->data, text->size ? text->size - 1 : 0) << '"'
                    << std::endl;
            }

            const std::initializer_list<const wchar_t*> signature_names{L"GetEnemiesInRange"};

            for (const wchar_t* name : describe_now ? signature_names : none)
            {
                if (auto* method = resolve(cls, name))
                {
                    auto narrowed = narrow(name, static_cast<std::uint32_t>(wcslen(name)));
                    dump_signature("    ", narrowed.c_str(), method);
                }
            }

            engine_vector player_position{};
            bool have_player_position = false;
            if (auto* method = resolve(cls, L"GetWorldPosition"))
            {
                player_position = method->call_native<engine_vector>(self);
                have_player_position = true;
                out << "    GetWorldPosition() = " << player_position.x << ", " << player_position.y << ", "
                    << player_position.z << std::endl;
            }

            // Enumerating NPCs.
            //
            // GetAllNPCs takes one out parameter - a TDynArray of CNewNPC
            // handles that the engine fills and owns. Its storage and a
            // reference on every handle in it belong to the engine and nothing
            // here releases either, so this runs ONCE rather than every round:
            // holding references would keep despawned NPCs alive.
            // This now runs EVERY round, which is the test. If the release
            // works, the engine's allocator hands back the same storage each
            // time; if it leaks, the pointer walks upward round after round.
            {
                if (auto* fn = resolve(g_class, L"GetAllNPCs"))
                {
                    red3lib::TDynArray<red3lib::Handle<void>> npcs{};
                    fn->call_native<void>(g_context, npcs);

                    out << "    GetAllNPCs() filled " << npcs.size << " entries, storage "
                        << static_cast<const void*>(npcs.entries) << std::endl;

                    std::uint32_t shown = 0;
                    for (std::uint32_t i = 0; describe_now && i < npcs.size && shown < 15; i++)
                    {
                        auto* npc = npcs.entries[i].get();
                        if (!npc || !readable(npc, 512))
                        {
                            continue;
                        }

                        auto* npc_class = red3lib::class_of(npc);
                        if (!npc_class || !readable(npc_class, sizeof(red3lib::CClass)))
                        {
                            continue;
                        }

                        shown++;

                        auto class_name = npc_class->name.to_wide();
                        out << "      [" << i << "] "
                            << narrow(class_name.data(), static_cast<std::uint32_t>(class_name.size()));

                        auto* npc_self = reinterpret_cast<red3lib::IScriptable*>(npc);

                        if (auto* method = npc_class->find_function(L"GetDisplayName"))
                        {
                            if (method->is_native())
                            {
                                red3lib::owned<red3lib::String> text(method->return_type(),
                                                                    method->call_native<red3lib::String>(npc_self));
                                if (text->data)
                                {
                                    out << "  name=" << narrow(text->data, text->size ? text->size - 1 : 0);
                                }
                            }
                        }

                        if (have_player_position)
                        {
                            if (auto* method = npc_class->find_function(L"GetWorldPosition"))
                            {
                                if (method->is_native())
                                {
                                    auto at = method->call_native<engine_vector>(npc_self);
                                    auto dx = at.x - player_position.x;
                                    auto dy = at.y - player_position.y;
                                    auto dz = at.z - player_position.z;
                                    out << "  " << std::sqrt(dx * dx + dy * dy + dz * dz) << "m away";
                                }
                            }
                        }

                        out << std::endl;
                    }

                    if (describe_now && npcs.size > shown)
                    {
                        out << "      (" << (npcs.size - shown) << " more not listed)" << std::endl;
                    }

                    // The direct leak test. If a reference were taken each
                    // round and never given back, the SAME NPC's refcount would
                    // climb by exactly one per round. Process memory cannot
                    // show this - the game's own streaming moves hundreds of
                    // megabytes between rounds and buries the signal.
                    //
                    // The printed count includes the reference this array is
                    // holding, so what matters is that it stays CONSTANT across
                    // rounds, not its absolute value.
                    // The nearest NPC, which is also the one most likely to
                    // be on screen where a oneliner can be seen.
                    if (have_player_position)
                    {
                        red3lib::Handle<void>* nearest = nullptr;
                        float nearest_distance = 0.0f;

                        for (std::uint32_t i = 0; i < npcs.size; i++)
                        {
                            auto* npc = npcs.entries[i].get();
                            if (!npc || !readable(npc, 512))
                            {
                                continue;
                            }

                            auto* npc_class = red3lib::class_of(npc);
                            if (!npc_class)
                            {
                                continue;
                            }

                            auto* pos = npc_class->find_function(L"GetWorldPosition");
                            if (!pos || !pos->is_native())
                            {
                                continue;
                            }

                            auto at = pos->call_native<engine_vector>(reinterpret_cast<red3lib::IScriptable*>(npc));
                            const auto dx = at.x - player_position.x;
                            const auto dy = at.y - player_position.y;
                            const auto dz = at.z - player_position.z;
                            const auto distance = std::sqrt(dx * dx + dy * dy + dz * dz);

                            if (!nearest || distance < nearest_distance)
                            {
                                nearest = &npcs.entries[i];
                                nearest_distance = distance;
                            }
                        }

                        if (nearest)
                        {
                            std::string who = "<unnamed>";
                            auto* npc_class = red3lib::class_of(nearest->get());
                            if (auto* name_fn = npc_class ? npc_class->find_function(L"GetDisplayName") : nullptr)
                            {
                                if (name_fn->is_native())
                                {
                                    red3lib::owned<red3lib::String> text(
                                        name_fn->return_type(),
                                        name_fn->call_native<red3lib::String>(
                                            reinterpret_cast<red3lib::IScriptable*>(nearest->get())));
                                    if (text->data)
                                    {
                                        who = narrow(text->data, text->size ? text->size - 1 : 0);
                                    }
                                }
                            }

                            static bool handle_probe_done = false;
                            if (!handle_probe_done)
                            {
                                handle_probe_done = true;

                                auto& player_handle = *reinterpret_cast<red3lib::Handle<void>*>(
                                    reinterpret_cast<std::uint8_t*>(g_context) + 48592);

                                out << "  handle-argument control:" << std::endl;

                                // Actors are where handle-taking natives live -
                                // the game class has none, which is why the
                                // first scan came up empty. Context is the NPC,
                                // and the handle argument is the player.
                                auto* npc_context = reinterpret_cast<red3lib::IScriptable*>(nearest->get());
                                probe_handle_argument(npc_class, npc_context, player_handle, *nearest);

                                out << "  second-argument control:" << std::endl;
                                probe_second_argument(g_context, *nearest);
                            }

                            speak_oneliner(*nearest, who, nearest_distance);
                        }
                    }

                    // Pinning one NPC does not survive: the first attempt
                    // tracked entries[0] and went quiet after two samples
                    // because that NPC streamed out as the player moved. So
                    // re-pick when the tracked one is gone, and say so - a
                    // sample is only comparable with the ones before it if the
                    // object is the same.
                    static void* tracked = nullptr;
                    const red3lib::Handle<void>* found = nullptr;

                    for (std::uint32_t i = 0; tracked && i < npcs.size; i++)
                    {
                        if (npcs.entries[i].get() == tracked)
                        {
                            found = &npcs.entries[i];
                            break;
                        }
                    }

                    if (!found && npcs.size > 0)
                    {
                        found = &npcs.entries[0];
                        tracked = found->get();
                        out << "      tracking NPC " << tracked << " (re-picked)" << std::endl;
                    }

                    if (found && found->block)
                    {
                        out << "      tracked NPC " << tracked << " refcount = " << found->block->references
                            << std::endl;
                    }

                    // The array's storage, and a reference on every handle in
                    // it, are the engine's. Handing the array back to its own
                    // type destructs each element - releasing all 38 handle
                    // references - and then frees the storage.
                    if (auto* type = fn->param_type(0))
                    {
                        const auto* storage = npcs.entries;
                        type->destruct(&npcs);
                        out << "      released the array (storage was " << static_cast<const void*>(storage)
                            << ", now entries " << static_cast<const void*>(npcs.entries) << " size " << npcs.size
                            << ")" << std::endl;
                    }
                    else
                    {
                        out << "      LEAKED: no RTTI type for the out parameter" << std::endl;
                    }
                }
            }
        }
    }

    if (auto* fn = resolve(g_class, L"GetEngineTimeAsSeconds"))
    {
        out << "  GetEngineTimeAsSeconds() = " << fn->call_native<float>(g_context) << "  (post-check)" << std::endl;
    }
}

} // namespace

RED3LIB_C_EXPORT bool RED3LIB_CALL Main(HMODULE aHandle, EMainReason aReason)
{
    switch (aReason)
    {
    case EMainReason::Load:
    {
        open_log(aHandle);
        out << "RED3lib example loaded" << std::endl;
        break;
    }
    case EMainReason::Unload:
    {
        out << "RED3lib example unloading" << std::endl;
        g_log.close();
        break;
    }
    }

    return true;
}

RED3LIB_C_EXPORT void RED3LIB_CALL Update()
{
    // Sample repeatedly as the game progresses. The previous one-shot version
    // fired at the very first tick - long before the world exists - so every
    // native legitimately had nothing to return. Rounds spanning menu, load and
    // in-world distinguish "too early" from "marshalling is wrong".
    constexpr int frames_between_rounds = 300;
    constexpr int max_rounds = 60;
    constexpr int max_scans = 40;

    static int frame = 0;
    static int scans = 0;
    static int rounds = 0;
    static bool finished = false;

    if (finished)
    {
        return;
    }

    if (frame++ % frames_between_rounds != 0)
    {
        return;
    }

    if (!locate())
    {
        if (++scans > max_scans)
        {
            finished = true;
            out << "RED3lib: no CR4Game instance after " << max_scans << " scans, giving up" << std::endl;
        }
        return;
    }

    run_round(++rounds);

    if (rounds >= max_rounds)
    {
        finished = true;
        out << std::endl << "probes complete (" << rounds << " rounds)" << std::endl;
    }
}

RED3LIB_C_EXPORT const char* RED3LIB_CALL Supports()
{
    return supported_version;
}
